### ISSUE TITLE
タイマーの効果音をわかりやすくする

### ISSUE THREAD

**Issue by sorarideblog** [sorarideblog/youtube-study-space#113]
今のポーンという低い音ではわかりづらいという意見がみられる。
代替の新しい効果音を用意する。

**Comment by o-torodesu** [comment]
新しい効果音は作るorフリー素材を使うどちらですか？

**Comment by sorarideblog** [comment]
> 新しい効果音は作るorフリー素材を使うどちらですか？

どちらでもOKです！

**Comment by o-torodesu** [comment]
考えてみます！

**Comment by o-torodesu** [comment]
[①.zip](https://github.com/sorarideblog/youtube-study-space/files/7843404/default.zip)

**Comment by o-torodesu** [comment]
こんなのどうでしょう？

**Comment by o-torodesu** [comment]
圧縮ファイルになっています！

**Comment by sorarideblog** [comment]
いいと思います、ありがとうございます！

ちなみに休憩の開始・終了が音だけでわかるといいのですが、たとえば2回連続でゴングが鳴るやつは簡単に作れそうでしょうか？
（注文？多くてすみません）

**Comment by o-torodesu** [comment]
全然OKです！作れますよ！

**Comment by o-torodesu** [comment]
すぐ作ってみます！

**Comment by o-torodesu** [comment]
[Chime.zip](https://github.com/sorarideblog/youtube-study-space/files/7843666/Chime.zip)
できました！

**Comment by sorarideblog** [comment]
ありがとうございます！
2回鳴るほうですが、最後のほうで音が途切れてる感を感じるのですが、もう少し余韻を伸ばして頂けませんか？

**Comment by o-torodesu** [comment]
できますよ！
明日の朝作ってまた送ります！

**Comment by sorarideblog** [comment]
[youtube-monitor_public_chime_chime2.zip](https://github.com/sorarideblog/youtube-study-space/files/7864181/youtube-monitor_public_chime_chime2.zip)
2回鳴るバージョンを作成してみました。

**Comment by sorarideblog** [comment]
従来の効果音と新しい効果音の比較動画を作り、アンケートを設置しました。
https://www.youtube.com/post/Ugkx1ncJDsnjHEQyiHQd3_rXOywXngXLl22i

**Comment by o-torodesu** [comment]
ありがとうございます！

**Comment by sorarideblog** [comment]
アンケートの結果から、ひとまず効果音は現状維持で進めたいと思います。
一旦クローズします。
