### ISSUE TITLE
NotionのサイトでYoutube埋め込みプレイヤーが正しく表示されない

### ISSUE THREAD

**Issue by shusann01116** [sorarideblog/youtube-study-space#198]
https://youtube-study-space.notion.site/e207f455ce0e48a584db4654b9b95776
にアクセスすると。

![image](https://user-images.githubusercontent.com/26602565/175564026-a65e13db-b673-4d6b-b5e2-9d16f35a2f6c.png)

**Comment by sorarideblog** [comment]
ありがとうございます！
動画を埋め込むつもりはなかったのですが、Notionの自動補完で動画が埋め込まれたようです。
ちなみにこれまでは、意図的にYoutube以外のサイトの埋め込みでは視聴できないように設定していましたが、特に理由はなかったので、これを機に有効にしてみました。

![image](https://user-images.githubusercontent.com/54093651/175566517-ea868131-2b90-43ea-9a91-ed2a231aea6a.png)
