### ISSUE TITLE
Golang Version

### ISSUE THREAD

**Issue by gangjun06** [sorarideblog/youtube-study-space#231]
https://github.com/sorarideblog/youtube-study-space/blob/dev/system/go.mod
```
module app.modules

>> go 1.14

require ...
```
Current this project is using go 1.14.
But [latest version](https://go.dev/dl/) of golang is go1.19.1.
Is there any special reason to use old version?
Because of old version, I can't use new golang features.

**Comment by sorarideblog** [comment]
> Is there any special reason to use old version?

No, actually I didn't care about the go.mod.
I will update the Go version to 1.19.
